name: CI - Build, Test, Scan
on:
  pull_request:
    branches: [ develop, main ]
    paths:
      - "frontend/**"
      - "product-service/**"
      - "order-service/**"
      - ".github/workflows/**"
  push:
    branches: [ develop ]
    paths:
      - "frontend/**"
      - "product-service/**"
      - "order-service/**"
      - ".github/workflows/**"

jobs:
  codeql:
    name: CodeQL
    permissions:
      contents: read
      security-events: write
    uses: github/codeql-action/.github/workflows/codeql.yml@v3
    with:
      languages: "javascript"

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci || echo "no package.json - skipping"
      - run: npm test --if-present

  build-product:
    needs: [test-frontend]
    uses: ./.github/workflows/build-docker-reusable.yml
    with:
      service_name: product
      context: product-service
      dockerfile: product-service/Dockerfile
      image: ecommerce/product-service
      push: false
    secrets: inherit

  build-order:
    needs: [test-frontend]
    uses: ./.github/workflows/build-docker-reusable.yml
    with:
      service_name: order
      context: order-service
      dockerfile: order-service/Dockerfile
      image: ecommerce/order-service
      push: false
    secrets: inherit
